name: ClicksPerSecond
version: 2.5
author: davidcubesvk
main: com.davidcubesvk.clicksPerSecond.ClicksPerSecond
api-version: 1.13
softdepend:
  - PlaceholderAPI
depend:
  - ProtocolLib
commands:
  cps:
    description: "Main command of ClicksPerSecond plugin."
    usage: /cps