name: ${project.name}
version: ${project.version}
author: dejvokep
main: dev.dejvokep.clickspersecond.ClicksPerSecond
description: ${project.description}
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ProtocolLib